# docker-compose.yml
# FundChamps — Base Compose (Prod + Dev Safe Defaults)

services:
  web:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - .:/app
      - ./app/data:/app/data
    environment:
      # Flask Core
      FLASK_ENV: ${FLASK_ENV:-production}
      FLASK_DEBUG: ${FLASK_DEBUG:-0}
      FLASK_CONFIG: ${FLASK_CONFIG:-app.config.ProductionConfig}
      SECRET_KEY: ${SECRET_KEY:-change_me_prod}

      # Database (Postgres default, fallback SQLite)
      DATABASE_URL: ${DATABASE_URL:-sqlite:////app/data/app.db}
      SQLALCHEMY_ECHO: ${SQLALCHEMY_ECHO:-0}

      # Email (SMTP / SendGrid safe defaults)
      MAIL_SERVER: ${MAIL_SERVER:-smtp}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USE_TLS: ${MAIL_USE_TLS:-1}
      MAIL_USERNAME: ${MAIL_USERNAME:-dev_null}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-dev_null}
      MAIL_SUPPRESS_SEND: ${MAIL_SUPPRESS_SEND:-0}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER:-"FundChamps <noreply@fundchamps.org>"}

      SENDGRID_USERNAME: ${SENDGRID_USERNAME:-dev_null}
      SENDGRID_PASSWORD: ${SENDGRID_PASSWORD:-dev_null}

      # Stripe / PayPal
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_prod}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY:-pk_test_prod}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_prod}
      STRIPE_API_KEY: ${STRIPE_API_KEY:-sk_test_1234567890}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID:-dev_null}
      PAYPAL_SECRET: ${PAYPAL_SECRET:-dev_null}

      # Redis / Realtime
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      SOCKETIO_ASYNC_MODE: ${SOCKETIO_ASYNC_MODE:-eventlet}
      SOCKETIO_MESSAGE_QUEUE: ${SOCKETIO_MESSAGE_QUEUE:-}

      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      WERKZEUG_LOG_LEVEL: ${WERKZEUG_LOG_LEVEL:-WARNING}

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  app_data:

