# docker-compose.override.yml
# FundChamps — Local Dev Overrides (Safe Defaults for All Env Vars)

services:
  web:
    build: .
    environment:
      # Flask Core
      FLASK_ENV: ${FLASK_ENV:-development}
      FLASK_DEBUG: ${FLASK_DEBUG:-1}
      SECRET_KEY: ${SECRET_KEY:-dev_secret_key}

      # Database
      DATABASE_URL: ${DATABASE_URL:-sqlite:////app/data/app.db}
      SQLALCHEMY_ECHO: ${SQLALCHEMY_ECHO:-0}

      # Email (SMTP / SendGrid fallbacks)
      MAIL_SERVER: ${MAIL_SERVER:-localhost}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USE_TLS: ${MAIL_USE_TLS:-1}
      MAIL_USERNAME: ${MAIL_USERNAME:-dev_null}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-dev_null}
      MAIL_SUPPRESS_SEND: ${MAIL_SUPPRESS_SEND:-1}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER:-"FundChamps Dev <noreply@local>"}

      SENDGRID_USERNAME: ${SENDGRID_USERNAME:-dev_null}
      SENDGRID_PASSWORD: ${SENDGRID_PASSWORD:-dev_null}

      # Stripe / PayPal
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_dev}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY:-pk_test_dev}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_dev}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID:-dev_null}
      PAYPAL_SECRET: ${PAYPAL_SECRET:-dev_null}

      # Redis / Realtime
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      SOCKETIO_ASYNC_MODE: ${SOCKETIO_ASYNC_MODE:-threading}
      SOCKETIO_MESSAGE_QUEUE: ${SOCKETIO_MESSAGE_QUEUE:-}

      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      WERKZEUG_LOG_LEVEL: ${WERKZEUG_LOG_LEVEL:-WARNING}

