from sqlalchemy import Text
"""Sync after Team dedupe

Revision ID: b0cd58a096f1
Revises: a187215f15ed
Create Date: 2025-08-15 12:42:51.591625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0cd58a096f1'
down_revision = 'a187215f15ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=True),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('ai_used', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_from_number'), ['from_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_to_number'), ['to_number'], unique=False)

    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_updated_at'), ['updated_at'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('team_name', sa.String(length=120), nullable=False),
    sa.Column('meta_description', sa.String(length=255), nullable=True),
    sa.Column('lang_code', sa.String(length=5), nullable=False),
    sa.Column('theme', sa.String(length=30), nullable=True),
    sa.Column('theme_color', sa.String(length=7), nullable=True),
    sa.Column('body_class', sa.String(length=255), nullable=True),
    sa.Column('og_title', sa.String(length=120), nullable=True),
    sa.Column('og_description', sa.String(length=255), nullable=True),
    sa.Column('og_image', sa.String(length=255), nullable=True),
    sa.Column('favicon', sa.String(length=255), nullable=True),
    sa.Column('apple_icon', sa.String(length=255), nullable=True),
    sa.Column('hero_image', sa.String(length=255), nullable=True),
    sa.Column('custom_css', sa.String(length=255), nullable=True),
    sa.Column('record', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('impact_stats', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_teams_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_uuid'), ['uuid'], unique=True)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_uuid'), ['uuid'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('donor_name', sa.String(length=120), nullable=True),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('campaign_goal_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_goal_id'], ['campaign_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_campaign_goal_id'), ['campaign_goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_sponsor_id'), ['sponsor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_uuid'), ['uuid'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_team_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_uuid'))
        batch_op.drop_index(batch_op.f('ix_transactions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_sponsor_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_deleted'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_campaign_goal_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_uuid'))
        batch_op.drop_index(batch_op.f('ix_players_updated_at'))
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_deleted'))
        batch_op.drop_index(batch_op.f('ix_players_created_at'))

    op.drop_table('players')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_uuid'))
        batch_op.drop_index(batch_op.f('ix_teams_updated_at'))
        batch_op.drop_index(batch_op.f('ix_teams_slug'))
        batch_op.drop_index(batch_op.f('ix_teams_deleted'))
        batch_op.drop_index(batch_op.f('ix_teams_created_at'))

    op.drop_table('teams')
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsors_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sponsors_name'))
        batch_op.drop_index(batch_op.f('ix_sponsors_deleted'))
        batch_op.drop_index(batch_op.f('ix_sponsors_created_at'))

    op.drop_table('sponsors')
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_logs_to_number'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_from_number'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_created_at'))

    op.drop_table('sms_logs')
    # ### end Alembic commands ###
