"""initial schema

Revision ID: 3a9db6782a68
Revises: 
Create Date: 2025-08-19 11:03:44.741620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a9db6782a68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_number', sa.String(length=32), nullable=True),
    sa.Column('to_number', sa.String(length=32), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ai_used', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_message_id', sa.String(length=80), nullable=True),
    sa.Column('provider_error_code', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(from_number) <= 32', name='ck_sms_from_len'),
    sa.CheckConstraint('length(to_number)   <= 32', name='ck_sms_to_len'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.create_index('ix_sms_logs_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_direction'), ['direction'], unique=False)
        batch_op.create_index('ix_sms_logs_from', ['from_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_from_number'), ['from_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_provider_message_id'), ['provider_message_id'], unique=False)
        batch_op.create_index('ix_sms_logs_status', ['status'], unique=False)
        batch_op.create_index('ix_sms_logs_to', ['to_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_to_number'), ['to_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_updated_at'), ['updated_at'], unique=False)

    op.create_table('sponsor_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surface', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('ua', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsor_clicks', schema=None) as batch_op:
        batch_op.create_index('ix_clicks_created', ['created_at'], unique=False)
        batch_op.create_index('ix_clicks_name', ['name'], unique=False)
        batch_op.create_index('ix_clicks_tenant_surface', ['tenant', 'surface'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_clicks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_clicks_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_clicks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_clicks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_clicks_surface'), ['surface'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_clicks_tenant'), ['tenant'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_clicks_updated_at'), ['updated_at'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('team_name', sa.String(length=120), nullable=False),
    sa.Column('meta_description', sa.String(length=255), nullable=True),
    sa.Column('lang_code', sa.String(length=5), nullable=False),
    sa.Column('theme', sa.String(length=30), nullable=True),
    sa.Column('theme_color', sa.String(length=7), nullable=True),
    sa.Column('og_title', sa.String(length=120), nullable=True),
    sa.Column('og_description', sa.String(length=255), nullable=True),
    sa.Column('og_image', sa.String(length=255), nullable=True),
    sa.Column('favicon', sa.String(length=255), nullable=True),
    sa.Column('apple_icon', sa.String(length=255), nullable=True),
    sa.Column('hero_image', sa.String(length=255), nullable=True),
    sa.Column('custom_css', sa.String(length=255), nullable=True),
    sa.Column('record', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('impact_stats', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_teams_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_uuid'), ['uuid'], unique=True)

    op.create_table('campaign_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('goal_amount', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('goal_amount >= 0', name='ck_cg_goal_nonneg'),
    sa.CheckConstraint('total >= 0', name='ck_cg_total_nonneg'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_goals_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_campaign_goals_team_active', ['team_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_uuid'), ['uuid'], unique=True)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_uuid'), ['uuid'], unique=True)

    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_sponsors_amount_nonneg'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_status'), ['status'], unique=False)
        batch_op.create_index('ix_sponsors_status_amount', ['status', 'amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_updated_at'), ['updated_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('tier', sa.String(length=40), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('campaign_goal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount_cents >= 0', name='ck_donations_amount_nonneg'),
    sa.ForeignKeyConstraint(['campaign_goal_id'], ['campaign_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_campaign_goal_id'), ['campaign_goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_donations_email', ['email'], unique=False)
        batch_op.create_index('ix_donations_goal', ['campaign_goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_donations_team_status', ['team_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_updated_at'), ['updated_at'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('donor_name', sa.String(length=120), nullable=True),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('campaign_goal_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount_cents >= 0', name='ck_tx_amount_nonneg'),
    sa.ForeignKeyConstraint(['campaign_goal_id'], ['campaign_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_campaign_goal_id'), ['campaign_goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_donor_email'), ['donor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_sponsor_id'), ['sponsor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_uuid'), ['uuid'], unique=True)
        batch_op.create_index('ix_tx_goal', ['campaign_goal_id'], unique=False)
        batch_op.create_index('ix_tx_sponsor', ['sponsor_id'], unique=False)
        batch_op.create_index('ix_tx_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_status')
        batch_op.drop_index('ix_tx_sponsor')
        batch_op.drop_index('ix_tx_goal')
        batch_op.drop_index(batch_op.f('ix_transactions_uuid'))
        batch_op.drop_index(batch_op.f('ix_transactions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_sponsor_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_donor_email'))
        batch_op.drop_index(batch_op.f('ix_transactions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_deleted'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_campaign_goal_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_donations_tier'))
        batch_op.drop_index('ix_donations_team_status')
        batch_op.drop_index(batch_op.f('ix_donations_team_id'))
        batch_op.drop_index('ix_donations_goal')
        batch_op.drop_index('ix_donations_email')
        batch_op.drop_index(batch_op.f('ix_donations_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_donations_deleted'))
        batch_op.drop_index(batch_op.f('ix_donations_created_at'))
        batch_op.drop_index(batch_op.f('ix_donations_campaign_goal_id'))

    op.drop_table('donations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_team_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsors_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sponsors_tier'))
        batch_op.drop_index(batch_op.f('ix_sponsors_team_id'))
        batch_op.drop_index('ix_sponsors_status_amount')
        batch_op.drop_index(batch_op.f('ix_sponsors_status'))
        batch_op.drop_index(batch_op.f('ix_sponsors_name'))
        batch_op.drop_index(batch_op.f('ix_sponsors_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_sponsors_deleted'))
        batch_op.drop_index(batch_op.f('ix_sponsors_created_at'))

    op.drop_table('sponsors')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_uuid'))
        batch_op.drop_index(batch_op.f('ix_players_updated_at'))
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_players_deleted'))
        batch_op.drop_index(batch_op.f('ix_players_created_at'))

    op.drop_table('players')
    with op.batch_alter_table('campaign_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_goals_uuid'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_updated_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_team_id'))
        batch_op.drop_index('ix_campaign_goals_team_active')
        batch_op.drop_index(batch_op.f('ix_campaign_goals_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_deleted'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_created_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_active'))

    op.drop_table('campaign_goals')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_uuid'))
        batch_op.drop_index(batch_op.f('ix_teams_updated_at'))
        batch_op.drop_index(batch_op.f('ix_teams_slug'))
        batch_op.drop_index(batch_op.f('ix_teams_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_teams_deleted'))
        batch_op.drop_index(batch_op.f('ix_teams_created_at'))

    op.drop_table('teams')
    with op.batch_alter_table('sponsor_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_clicks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sponsor_clicks_tenant'))
        batch_op.drop_index(batch_op.f('ix_sponsor_clicks_surface'))
        batch_op.drop_index(batch_op.f('ix_sponsor_clicks_name'))
        batch_op.drop_index(batch_op.f('ix_sponsor_clicks_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_sponsor_clicks_deleted'))
        batch_op.drop_index(batch_op.f('ix_sponsor_clicks_created_at'))
        batch_op.drop_index('ix_clicks_tenant_surface')
        batch_op.drop_index('ix_clicks_name')
        batch_op.drop_index('ix_clicks_created')

    op.drop_table('sponsor_clicks')
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_logs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_to_number'))
        batch_op.drop_index('ix_sms_logs_to')
        batch_op.drop_index('ix_sms_logs_status')
        batch_op.drop_index(batch_op.f('ix_sms_logs_provider_message_id'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_provider'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_from_number'))
        batch_op.drop_index('ix_sms_logs_from')
        batch_op.drop_index(batch_op.f('ix_sms_logs_direction'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_deleted'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_created_at'))
        batch_op.drop_index('ix_sms_logs_created')

    op.drop_table('sms_logs')
    # ### end Alembic commands ###
