"""create donations table

Revision ID: 454175e7b815
Revises: a92e49a50f9f
Create Date: 2025-08-16 20:27:24.155096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454175e7b815'
down_revision = 'a92e49a50f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('tier', sa.String(length=40), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('campaign_goal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_goal_id'], ['campaign_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_campaign_goal_id'), ['campaign_goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('body_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_class', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_donations_tier'))
        batch_op.drop_index(batch_op.f('ix_donations_team_id'))
        batch_op.drop_index(batch_op.f('ix_donations_email'))
        batch_op.drop_index(batch_op.f('ix_donations_deleted'))
        batch_op.drop_index(batch_op.f('ix_donations_campaign_goal_id'))

    op.drop_table('donations')
    # ### end Alembic commands ###
