"""update campaign_goals indexes

Revision ID: 9308db77cfb5
Revises: 62587335dfe8
Create Date: 2025-08-19 15:07:57.128123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9308db77cfb5'
down_revision = '62587335dfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_uuid'), ['uuid'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('donor_name', sa.String(length=120), nullable=True),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('campaign_goal_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount_cents >= 0', name='ck_tx_amount_nonneg'),
    sa.ForeignKeyConstraint(['campaign_goal_id'], ['campaign_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_campaign_goal_id'), ['campaign_goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_donor_email'), ['donor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_sponsor_id'), ['sponsor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_uuid'), ['uuid'], unique=True)
        batch_op.create_index('ix_tx_goal', ['campaign_goal_id'], unique=False)
        batch_op.create_index('ix_tx_sponsor', ['sponsor_id'], unique=False)
        batch_op.create_index('ix_tx_status', ['status'], unique=False)

    with op.batch_alter_table('campaign_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.alter_column('goal_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_campaign_goals_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_campaign_goals_team_active', ['team_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_goals_uuid'), ['uuid'], unique=True)
        batch_op.create_index('uq_campaign_goals_active_per_team', ['team_id'], unique=True, sqlite_where=sa.text('active = 1'), postgresql_where=sa.text('active = true'))
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=160), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=160), nullable=False))
        batch_op.add_column(sa.Column('tier', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('amount_cents', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('campaign_goal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_donations_campaign_goal_id'), ['campaign_goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_donations_email', ['email'], unique=False)
        batch_op.create_index('ix_donations_goal', ['campaign_goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_donations_team_status', ['team_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'campaign_goals', ['campaign_goal_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('message')
        batch_op.drop_column('donor_name')
        batch_op.drop_column('amount')

    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_logs_from_number'), ['from_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_provider'), ['provider'], unique=False)

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_sponsors_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_status'), ['status'], unique=False)
        batch_op.create_index('ix_sponsors_status_amount', ['status', 'amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_updated_at'), ['updated_at'], unique=False)
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sponsors_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sponsors_team_id'))
        batch_op.drop_index('ix_sponsors_status_amount')
        batch_op.drop_index(batch_op.f('ix_sponsors_status'))
        batch_op.drop_index(batch_op.f('ix_sponsors_name'))
        batch_op.drop_index(batch_op.f('ix_sponsors_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_sponsors_deleted'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('tier',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('status')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_logs_provider'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_from_number'))

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('donor_name', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('message', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_donations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_donations_tier'))
        batch_op.drop_index('ix_donations_team_status')
        batch_op.drop_index(batch_op.f('ix_donations_team_id'))
        batch_op.drop_index('ix_donations_goal')
        batch_op.drop_index('ix_donations_email')
        batch_op.drop_index(batch_op.f('ix_donations_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_donations_deleted'))
        batch_op.drop_index(batch_op.f('ix_donations_campaign_goal_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('campaign_goal_id')
        batch_op.drop_column('team_id')
        batch_op.drop_column('logo_path')
        batch_op.drop_column('amount_cents')
        batch_op.drop_column('tier')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    with op.batch_alter_table('campaign_goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('uq_campaign_goals_active_per_team', sqlite_where=sa.text('active = 1'), postgresql_where=sa.text('active = true'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_uuid'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_updated_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_team_id'))
        batch_op.drop_index('ix_campaign_goals_team_active')
        batch_op.drop_index(batch_op.f('ix_campaign_goals_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_deleted'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_created_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_goals_active'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('goal_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('description')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('active')
        batch_op.drop_column('total')
        batch_op.drop_column('team_id')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_status')
        batch_op.drop_index('ix_tx_sponsor')
        batch_op.drop_index('ix_tx_goal')
        batch_op.drop_index(batch_op.f('ix_transactions_uuid'))
        batch_op.drop_index(batch_op.f('ix_transactions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_sponsor_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_donor_email'))
        batch_op.drop_index(batch_op.f('ix_transactions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_deleted'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_campaign_goal_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_team_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_uuid'))
        batch_op.drop_index(batch_op.f('ix_players_updated_at'))
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_players_deleted'))
        batch_op.drop_index(batch_op.f('ix_players_created_at'))

    op.drop_table('players')
    # ### end Alembic commands ###
