version: "3.9"
services:
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/fundchamps
      - SECRET_KEY=change-me
      - FLASK_ENV=production
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fundchamps
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
